language: node_js
node_js:
- '10'
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_7286f759eb6e_key -iv $encrypted_7286f759eb6e_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_congfig ~/.ssh/config
- git config --global user.name 'gitchenhouse'
- git config --global user.email b9903231@gapps.ntust.edu.tw
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- sed -i'' "/^ *repo/s~github\.com~${git_token}@github.com~" _config.yml
- hexo deploy
